name: slow_frp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter: 
    sdk: flutter
  get: ^4.6.6
  bitsdojo_window: ^0.1.5
  tray_manager: ^0.2.0
  window_manager: ^0.3.7
  dio: ^5.1.0
  archive: ^3.3.6
  flutter_console_widget:
    git:
      url: https://github.com/buming98/flutter_console.git
  sidebarx: ^0.16.3
  pluto_grid: ^7.0.2
  path_provider: ^2.1.1
  contained_tab_bar_view: ^0.8.0
  url_launcher: ^6.2.2

dev_dependencies: 
  flutter_lints: 3.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/

